### ISSUE TITLE
[Bug]: Failed to start oceanbase-ce container on Macbook with M1 chip

### ISSUE THREAD

**Issue by whhe** [oceanbase/docker-images#34]
### Describe the bug

When starting oceanbase container on a Macbook with an M1 chip, it will get stuck for a while after log `observer program health check ok`, and fail in the end.

### Environment

macOS 14.5 (23F79) on MacBook Pro with M1 chip. 
Docker Desktop 4.30.0 (149282)
Docker image: `quay.io/oceanbase/oceanbase-ce:4.2.1-lts`

### Fast reproduce steps

`docker run --name obce -e MODE=mini -e OB_SYS_PASSWORD=123456 -e OB_TENANT_PASSWORD=654321 -d quay.io/oceanbase/oceanbase-ce:4.2.1-lts`

### Additional context

[/root/.obd/log/obd](https://github.com/user-attachments/files/16446022/obd.log)
[/root/ob](https://github.com/user-attachments/files/16446027/ob.zip)

**Comment by chris-sun-star** [comment]
optimized the building process and tested with the latest 4.2.1 image, it's working now
