### ISSUE TITLE
[Bug]: Got x86 OS in the arm64 version of oceanbase-ce container

### ISSUE THREAD

**Issue by whhe** [oceanbase/docker-images#35]
### Describe the bug

Start an oceanbase-ce arm64 container, and execute 'uname -m' in it, I got 'x86_64'.

### Environment

oceanbase/oceanbase-ce:4.2.1-lts

### Fast reproduce steps

uname -m

**Comment by zchazc** [comment]
I encountered an "exec /usr/bin/bash: exec format error" when trying to use this image on a Raspberry Pi. After some search, I believe this might be the reason. I can't even execute `docker exec -it oceanbase/oceanbase-ce uname -m`.

**Comment by zchazc** [comment]
OS: Raspbian (Debian)
docker tag : latest（sha256:7ad269869c872c9483de5093f0d3119c4956f634f37373e1769e1e5632324145）

**Comment by zchazc** [comment]
> Which tag did you use for this testing and what is your OS?您在本次测试中使用了哪个标签以及您的操作系统是什么？

OS: Raspbian (Debian)
docker tag : latest（sha256:7ad269869c872c9483de5093f0d3119c4956f634f37373e1769e1e5632324145）

**Comment by whhe** [comment]
> > Which tag did you use for this testing and what is your OS?您在本次测试中使用了哪个标签以及您的操作系统是什么？
> 
> OS: Raspbian (Debian) docker tag : latest（sha256:7ad269869c872c9483de5093f0d3119c4956f634f37373e1769e1e5632324145）

Are you testing it on arm64 machine? The existing arm64 image imported the wrong base image of anolis, and we are trying to fix it in https://github.com/oceanbase/docker-images/pull/39, you can try the new image after it's merged.
